version: '1'

services:
  server:
    image: anojan1007/collabee-server:latest
    ports:
      - 4000:4000
  client:
    image: anojan1007/collabee-client:latest
    ports:
      - 3000:3000
  mysql:
    image: "mysql:5.7.10"
    command: [ "mysqld",
               "--character-set-server=utf8mb4",
               "--collation-server=utf8mb4_unicode_ci",
               "--bind-address=0.0.0.0",
               "--default_authentication_plugin=mysql_native_password" ]
    ports:
      - "3307:3306"
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/mysql
      - type: bind
        source: ./certs
        target: /etc/certs/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "collabee"
      MYSQL_USER: "valere_collabee"
      MYSQL_PASSWORD: "collabee"
      MYSQL_DATABASE: "collabee"