version: '3.7'

services:
  server:
    image: anojan1007/collabee-server:latest
    ports:
      - 4000:4000
  client:
    image: anojan1007/collabee-client:latest
    ports:
      - 3000:3000
  mysql:
    image: "mysql:5.7.10"
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "collabee"
      MYSQL_USER: "valere_collabee"
      MYSQL_PASSWORD: "collabee"
      MYSQL_DATABASE: "collabee"