version: '3.7'

services:
  server:
    image: anojan1007/collabee-server:latest
    ports:
      - 4000:5000
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - SECRET_TOKEN_USER=${SECRET_TOKEN_USER}
      - BACKEND_API_AUTHORIZATION=${BACKEND_API_AUTHORIZATION}
      - NODE_ENV=production
  client:
    image: anojan1007/collabee-client:latest
    ports:
      - 3000:3000
  mysql:
    image: "mysql:5.7.10"
    volumes:
      - ./staging-database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "collabee"
      MYSQL_USER: "valere_collabee"
      MYSQL_PASSWORD: "collabee"
      MYSQL_DATABASE: "collabee"
  nginx:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  